# Generated by Django 4.2.7 on 2023-11-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClincApp', '0005_rename_patient_appointments_patient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='slot_id',
            new_name='slot',
        ),
    ]
