# Generated by Django 4.2.7 on 2023-11-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClincApp', '0007_rename_doctor_id_doctorslots_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='slot',
            new_name='slot_id',
        ),
    ]
