apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mydatabase
spec:
  replicas: 1
  selector:
    app: mydatabase
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: mydatabase
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        securityContext:
          runAsUser: 0  # Run the container as root
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: database
        - name: POSTGRES_DATABASE
          value: Clinc