# Generated by Django 4.2.7 on 2023-11-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClincApp', '0002_alter_doctorslots_status_alter_users_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userType',
            new_name='user_role',
        ),
    ]
