# Generated by Django 4.2.7 on 2023-11-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClincApp', '0003_rename_usertype_users_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='slot_id',
            new_name='slot',
        ),
    ]
