# Generated by Django 4.2.7 on 2023-11-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClincApp', '0004_rename_patient_id_appointments_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='slot',
            new_name='slot_id',
        ),
    ]
