# Generated by Django 4.2.7 on 2023-11-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClincApp', '0006_rename_patient_id_appointments_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorslots',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
